//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4YolMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashBoxLog
    {
        public int Id { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> CashBoxCategoryId { get; set; }
        public decimal Mebleg { get; set; }
        public Nullable<int> FirmaId { get; set; }
        public System.DateTime Tarix { get; set; }
        public string Description { get; set; }
    
        public virtual CashBoxCategory CashBoxCategory { get; set; }
        public virtual Firma Firma { get; set; }
    }
}
