//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4YolMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KassaEmeliyat
    {
        public int Id { get; set; }
        public System.DateTime Tarix { get; set; }
        public decimal Mebleg { get; set; }
        public bool Gelir_Xerc_ { get; set; }
        public Nullable<int> PurchaseId { get; set; }
        public Nullable<int> OrderId { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Purchase Purchase { get; set; }
    }
}
