//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4YolMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoneyTransfer
    {
        public int Id { get; set; }
        public Nullable<int> FromCashBoxId { get; set; }
        public Nullable<int> ToCashBoxId { get; set; }
        public Nullable<bool> Status { get; set; }
        public decimal Mebleg { get; set; }
    
        public virtual CashBox CashBox { get; set; }
        public virtual CashBox CashBox1 { get; set; }
    }
}
