//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4YolMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int Id { get; set; }
        public decimal SatisMeblegi { get; set; }
        public decimal Say { get; set; }
        public int ProductId { get; set; }
        public int OrderId { get; set; }
        public bool Status { get; set; }
        public Nullable<decimal> MehsulMeblegi { get; set; }
        public Nullable<decimal> Qazanc { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
