//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4YolMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Purchase()
        {
            this.KassaEmeliyats = new HashSet<KassaEmeliyat>();
            this.PurchaseItems = new HashSet<PurchaseItem>();
            this.Stocks = new HashSet<Stock>();
        }
    
        public int Id { get; set; }
        public System.DateTime Tarix { get; set; }
        public decimal ToplamMebleg { get; set; }
        public decimal OdenilenMebleg { get; set; }
        public bool Status { get; set; }
        public int FirmaId { get; set; }
        public Nullable<bool> Veziyyet { get; set; }
    
        public virtual Firma Firma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KassaEmeliyat> KassaEmeliyats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseItem> PurchaseItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock> Stocks { get; set; }
    }
}
