//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4YolMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseItem
    {
        public int Id { get; set; }
        public decimal AlisMebleg { get; set; }
        public System.DateTime IstehsalTarixi { get; set; }
        public System.DateTime BitmeTarixi { get; set; }
        public int ProductId { get; set; }
        public Nullable<int> PurchaseId { get; set; }
        public decimal Say_Ceki_ { get; set; }
        public bool Status { get; set; }
    
        public virtual Purchase Purchase { get; set; }
        public virtual Product Product { get; set; }
    }
}
